version: '3'
services:
    app:
        build: .
        ports:
            - 8080:8080
        environment:
            FLASK_ENV: development
        volumes:
            - .:/app
    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: Users
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: hahaha123
        ports:
            - 5432:5432
        volumes:
            - ./src/db/users_schema.sql:/docker-entrypoint-initdb.d/users_schema.sql
            - ./build/db:/var/lib/postgresql/data
