version: '3'
services:
    app_main:
        build:
            context: .
            dockerfile: docker/app_main.Dockerfile
        networks:
            usernet:
                ipv4_address: "172.10.10.1"
        ports:
            - 3001:3001
        volumes:
            - .:/app
    app_test:
        build:
            context: .
            dockerfile: docker/app_test.Dockerfile
        volumes:
            - .:/app
    db:
        build:
            context: .
            dockerfile: docker/db.Dockerfile
        networks:
            usernet:
                ipv4_address: "172.10.10.2"
        ports:
            - 5432:5432
        volumes:
            - ./build/db:/var/lib/postgresql/data

networks:
    usernet:
        ipam:
            driver: default
            config:
                - subnet: 172.10.10.0/16